import Head from "next/head";

export default function PageLayout({ children, title = "My App" }) {
  return (
    <>
       <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>My App 🎶</h1>
      </header>
      <main>
        {children}
      </main>
    </>
  );
}   